// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {nav} from '../models';

export function AddFile(arg1:string):Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function NBConnected(arg1:string,arg2:boolean):Promise<void>;

export function NBContribute(arg1:string,arg2:string):Promise<void>;

export function NBError(arg1:string,arg2:string):Promise<void>;

export function Preview(arg1:string,arg2:boolean):Promise<nav.PreviewInfo>;

export function ReadDirFiles(arg1:string,arg2:boolean):Promise<Array<nav.FileInfo>>;

export function WD():Promise<nav.WorkingDir>;
