// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile(arg1) {
  return window['go']['main']['App']['AddFile'](arg1);
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function NBConnected(arg1, arg2) {
  return window['go']['main']['App']['NBConnected'](arg1, arg2);
}

export function NBContribute(arg1, arg2) {
  return window['go']['main']['App']['NBContribute'](arg1, arg2);
}

export function NBError(arg1, arg2) {
  return window['go']['main']['App']['NBError'](arg1, arg2);
}

export function Preview(arg1, arg2) {
  return window['go']['main']['App']['Preview'](arg1, arg2);
}

export function ReadDirFiles(arg1, arg2) {
  return window['go']['main']['App']['ReadDirFiles'](arg1, arg2);
}

export function WD() {
  return window['go']['main']['App']['WD']();
}
